.TH "help Directory Reference" 3 "Sun Oct 13 2013" "Version 3.6.99" "liblinphone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
help Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbuddy_status\&.c\fP"
.br
.ti -1c
.RI "file \fBchatroom\&.c\fP"
.br
.ti -1c
.RI "file \fBhelloworld\&.c\fP"
.br
.ti -1c
.RI "file \fBnotify\&.c\fP"
.br
.ti -1c
.RI "file \fBregistration\&.c\fP"
.br
.in -1c
