/** \file
 *  This C source file was generated by $ANTLR version 3.2 Sep 23, 2009 12:02:23
 *
 *     -  From the grammar source file : /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g
 *     -                            On : 2013-10-13 10:59:34
 *     -                 for the lexer : belle_sip_messageLexerLexer *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "belle_sip_messageLexer.h"
/* ----------------------------------------- */


/** String literals used by belle_sip_messageLexer that we must do things like MATCHS() with.
 *  C will normally just lay down 8 bit characters, and you can use L"xxx" to
 *  get wchar_t, but wchar_t is 16 bits on Windows, which is not UTF32 and so
 *  we perform this little trick of defining the literals as arrays of UINT32
 *  and passing in the address of these.
 */
static ANTLR3_UCHAR	lit_1[]  = { 0x3A, 0x3A,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_2[]  = { 0x0D, 0x0A,  ANTLR3_STRING_TERMINATOR};




/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */
 
#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pbelle_sip_messageLexer_##scope##_SCOPE
#define SCOPE_STACK(scope)  pbelle_sip_messageLexer_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pbelle_sip_messageLexer_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pbelle_sip_messageLexer_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

 
/* Macros for accessing things in a lexer
 */
#undef	    LEXER
#undef	    RECOGNIZER		    
#undef	    RULEMEMO		    
#undef	    GETCHARINDEX
#undef	    GETLINE
#undef	    GETCHARPOSITIONINLINE
#undef	    EMIT
#undef	    EMITNEW
#undef	    MATCHC
#undef	    MATCHS
#undef	    MATCHRANGE
#undef	    LTOKEN
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    INPUT
#undef	    STRSTREAM
#undef	    LA
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    LRECOVER
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    BACKTRACKING
#undef		MATCHANY
#undef		MEMOIZE
#undef		HAVEPARSEDRULE
#undef		GETTEXT
#undef		INDEX
#undef		SEEK
#undef		PUSHSTREAM
#undef		POPSTREAM
#undef		SETTEXT
#undef		SETTEXT8

#define	    LEXER					ctx->pLexer
#define	    RECOGNIZER			    LEXER->rec
#define		LEXSTATE				RECOGNIZER->state
#define		TOKSOURCE				LEXSTATE->tokSource
#define	    GETCHARINDEX()			LEXER->getCharIndex(LEXER)
#define	    GETLINE()				LEXER->getLine(LEXER)
#define	    GETTEXT()				LEXER->getText(LEXER)
#define	    GETCHARPOSITIONINLINE() LEXER->getCharPositionInLine(LEXER)
#define	    EMIT()					LEXSTATE->type = _type; LEXER->emit(LEXER)
#define	    EMITNEW(t)				LEXER->emitNew(LEXER, t)
#define	    MATCHC(c)				LEXER->matchc(LEXER, c)
#define	    MATCHS(s)				LEXER->matchs(LEXER, s)
#define	    MATCHRANGE(c1,c2)	    LEXER->matchRange(LEXER, c1, c2)
#define	    MATCHANY()				LEXER->matchAny(LEXER)
#define	    LTOKEN  				LEXSTATE->token
#define	    HASFAILED()				(LEXSTATE->failed == ANTLR3_TRUE)
#define	    BACKTRACKING			LEXSTATE->backtracking
#define	    FAILEDFLAG				LEXSTATE->failed
#define	    INPUT					LEXER->input
#define	    STRSTREAM				INPUT
#define		ISTREAM					INPUT->istream
#define		INDEX()					ISTREAM->index(ISTREAM)
#define		SEEK(n)					ISTREAM->seek(ISTREAM, n)
#define	    EOF_TOKEN				&(LEXSTATE->tokSource->eofToken)
#define	    HASEXCEPTION()			(LEXSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				LEXSTATE->exception
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    LRECOVER()				LEXER->recover(LEXER)
#define	    MARK()					ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define		MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define		HAVEPARSEDRULE(r)		RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		PUSHSTREAM(str)			LEXER->pushCharStream(LEXER, str)
#define		POPSTREAM()				LEXER->popCharStream(LEXER)
#define		SETTEXT(str)			LEXSTATE->text = str
#define		SKIP()					LEXSTATE->token = &(TOKSOURCE->skipToken)
#define		USER1					LEXSTATE->user1
#define		USER2					LEXSTATE->user2
#define		USER3					LEXSTATE->user3
#define		CUSTOM					LEXSTATE->custom
#define		RULEMEMO				LEXSTATE->ruleMemo
#define		DBG						RECOGNIZER->debugger

/* If we have been told we can rely on the standard 8 bit or 16 bit input
 * stream, then we can define our macros to use the direct pointers
 * in the input object, which is much faster than indirect calls. This
 * is really only significant to lexers with a lot of fragment rules (which
 * do not place LA(1) in a temporary at the moment) and even then
 * only if there is a lot of input (order of say 1M or so).
 */
#if	defined(ANTLR3_INLINE_INPUT_ASCII) || defined(ANTLR3_INLINE_INPUT_UTF16)

# ifdef	ANTLR3_INLINE_INPUT_ASCII

/* 8 bit "ASCII" (actually any 8 bit character set) */

#  define	    NEXTCHAR			((pANTLR3_UINT8)(INPUT->nextChar))
#  define	    DATAP				((pANTLR3_UINT8)(INPUT->data))

# else

#  define	    NEXTCHAR			((pANTLR3_UINT16)(INPUT->nextChar)) 
#  define	    DATAP				((pANTLR3_UINT16)(INPUT->data))

# endif

# define	    LA(n) ((NEXTCHAR + n) > (DATAP + INPUT->sizeBuf) ? ANTLR3_CHARSTREAM_EOF : (ANTLR3_UCHAR)(*(NEXTCHAR + n - 1)))
# define	    CONSUME()											\
{																	\
    if	(NEXTCHAR < (DATAP + INPUT->sizeBuf))						\
    {																\
		INPUT->charPositionInLine++;								\
		if  ((ANTLR3_UCHAR)(*NEXTCHAR) == INPUT->newlineChar)		\
		{															\
			INPUT->line++;											\
			INPUT->charPositionInLine	= 0;						\
			INPUT->currentLine		= (void *)(NEXTCHAR + 1);		\
		}															\
		INPUT->nextChar = (void *)(NEXTCHAR + 1);					\
    }																\
}

#else

// Pick up the input character by calling the input stream implementation.
//
#define	    CONSUME()				INPUT->istream->consume(INPUT->istream)
#define	    LA(n)					INPUT->istream->_LA(INPUT->istream, n)

#endif
#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/* Forward declare the locally static matching functions we have generated and any predicate functions.
 */
static ANTLR3_INLINE  void	mT__24    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mT__25    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mT__26    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mT__27    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mT__28    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mT__29    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mT__30    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mT__31    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mT__32    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mT__33    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mT__34    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mT__35    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mT__36    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mT__37    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mT__38    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mT__39    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mT__40    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mT__41    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mT__42    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mCOMMON_CHAR    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mHEX_CHAR    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mDIGIT    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mCRLF    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mHTAB    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mDQUOTE    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mLWS    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mPLUS    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mCOLON    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mSEMI    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mCOMMA    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mLAQUOT    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mRAQUOT    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mRPAREN    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mLPAREN    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mEQUAL    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mSLASH    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mSTAR    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mSP    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mOCTET    (pbelle_sip_messageLexer ctx);
static ANTLR3_INLINE  void	mTokens    (pbelle_sip_messageLexer ctx);
static void	belle_sip_messageLexerFree(pbelle_sip_messageLexer ctx);

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */



static void
belle_sip_messageLexerFree  (pbelle_sip_messageLexer ctx)
{
    LEXER->free(LEXER);
    
    ANTLR3_FREE(ctx);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "/Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}

/** \brief Create a new lexer called belle_sip_messageLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \return 
 *     - Success pbelle_sip_messageLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pbelle_sip_messageLexer belle_sip_messageLexerNew         
(pANTLR3_INPUT_STREAM instream)
{
	// See if we can create a new lexer with the standard constructor
	//
	return belle_sip_messageLexerNewSSD(instream, NULL);
}

/** \brief Create a new lexer called belle_sip_messageLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \param[state] state Previously created shared recognizer stat
 * \return 
 *     - Success pbelle_sip_messageLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pbelle_sip_messageLexer belle_sip_messageLexerNewSSD         
(pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pbelle_sip_messageLexer ctx; // Context structure we will build and return

    ctx = (pbelle_sip_messageLexer) ANTLR3_CALLOC(1, sizeof(belle_sip_messageLexer));

    if  (ctx == NULL)
    {
        // Failed to allocate memory for lexer context
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * in base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 lexer function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function. 
     *
     * We don't use the macros defined in belle_sip_messageLexer.h here so you can get a sense
     * of what goes where.
     */
    
    /* Create a base lexer, using the supplied input stream
     */
    ctx->pLexer	= antlr3LexerNewStream(ANTLR3_SIZE_HINT, instream, state);
    
    /* Check that we allocated the memory correctly
     */
    if	(ctx->pLexer == NULL)
    {
		ANTLR3_FREE(ctx);
		return  NULL;
    }
    /* Install the implementation of our belle_sip_messageLexer interface
     */
    ctx->mT__24	= mT__24;
    ctx->mT__25	= mT__25;
    ctx->mT__26	= mT__26;
    ctx->mT__27	= mT__27;
    ctx->mT__28	= mT__28;
    ctx->mT__29	= mT__29;
    ctx->mT__30	= mT__30;
    ctx->mT__31	= mT__31;
    ctx->mT__32	= mT__32;
    ctx->mT__33	= mT__33;
    ctx->mT__34	= mT__34;
    ctx->mT__35	= mT__35;
    ctx->mT__36	= mT__36;
    ctx->mT__37	= mT__37;
    ctx->mT__38	= mT__38;
    ctx->mT__39	= mT__39;
    ctx->mT__40	= mT__40;
    ctx->mT__41	= mT__41;
    ctx->mT__42	= mT__42;
    ctx->mCOMMON_CHAR	= mCOMMON_CHAR;
    ctx->mHEX_CHAR	= mHEX_CHAR;
    ctx->mDIGIT	= mDIGIT;
    ctx->mCRLF	= mCRLF;
    ctx->mHTAB	= mHTAB;
    ctx->mDQUOTE	= mDQUOTE;
    ctx->mLWS	= mLWS;
    ctx->mPLUS	= mPLUS;
    ctx->mCOLON	= mCOLON;
    ctx->mSEMI	= mSEMI;
    ctx->mCOMMA	= mCOMMA;
    ctx->mLAQUOT	= mLAQUOT;
    ctx->mRAQUOT	= mRAQUOT;
    ctx->mRPAREN	= mRPAREN;
    ctx->mLPAREN	= mLPAREN;
    ctx->mEQUAL	= mEQUAL;
    ctx->mSLASH	= mSLASH;
    ctx->mSTAR	= mSTAR;
    ctx->mSP	= mSP;
    ctx->mOCTET	= mOCTET;
    ctx->mTokens	= mTokens;
    
    /** When the nextToken() call is made to this lexer's pANTLR3_TOKEN_SOURCE
     *  it will call mTokens() in this generated code, and will pass it the ctx
     * pointer of this lexer, not the context of the base lexer, so store that now.
     */
    ctx->pLexer->ctx	    = ctx;
    
    /**Install the token matching function
     */
    ctx->pLexer->mTokens = (void (*) (void *))(mTokens);
    
    ctx->getGrammarFileName	= getGrammarFileName;
    ctx->free		= belle_sip_messageLexerFree;

    
    


    /* Return the newly built lexer to the caller
     */
    return  ctx;
}

/* =========================================================================
 * DFA tables for the lexer
 */
/** Static dfa state tables for Cyclic dfa:
 *    1431:9: ( ( SP )* CRLF )?
 */
static const ANTLR3_INT32 dfa2_eot[4] =
    {
	-1, 3, -1, -1
    };
static const ANTLR3_INT32 dfa2_eof[4] =
    {
	-1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa2_min[4] =
    {
	13, 13, -1, -1
    };
static const ANTLR3_INT32 dfa2_max[4] =
    {
	32, 32, -1, -1
    };
static const ANTLR3_INT32 dfa2_accept[4] =
    {
	-1, -1, 1, 2
    };
static const ANTLR3_INT32 dfa2_special[4] =
    {	
	-1, -1, -1, -1
    };

/** Used when there is no transition table entry for a particular state */
#define dfa2_T_empty	    NULL

static const ANTLR3_INT32 dfa2_T0[] =
    {
	2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, 1
    };

/* Transition tables are a table of sub tables, with some tables
 * reused for efficiency.
 */
static const ANTLR3_INT32 * const dfa2_transitions[] =
{
    dfa2_T0, dfa2_T0, dfa2_T_empty, dfa2_T_empty	
};


/* Declare tracking structure for Cyclic DFA 2
 */
static
ANTLR3_CYCLIC_DFA cdfa2
    =	{
	    2,		    /* Decision number of this dfa	    */
	    /* Which decision this represents:   */
	    (const pANTLR3_UCHAR)"1431:9: ( ( SP )* CRLF )?",	
	    (CDFA_SPECIAL_FUNC) antlr3dfaspecialStateTransition,	/* Default special state transition function	*/
	    antlr3dfaspecialTransition,		/* DFA specialTransition is currently just a default function in the runtime */
	    antlr3dfapredict,			/* DFA simulator function is in the runtime */
	    dfa2_eot,	    /* EOT table			    */
	    dfa2_eof,	    /* EOF table			    */
	    dfa2_min,	    /* Minimum tokens for each state    */
	    dfa2_max,	    /* Maximum tokens for each state    */
	    dfa2_accept,	/* Accept table			    */
	    dfa2_special,	/* Special transition states	    */
	    dfa2_transitions	/* Table of transition tables	    */

	};	    
/* End of Cyclic DFA 2
 * ---------------------
 */ 
/* =========================================================================
 * End of DFA tables for the lexer
 */ 

/* =========================================================================
 * Functions to match the lexer grammar defined tokens from the input stream
 */

//   Comes from: 7:7: ( '@' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__24
 *
 * Looks to match the characters the constitute the token T__24
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__24(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__24;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:7:7: ( '@' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:7:9: '@'
    {
        MATCHC('@'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__24Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__24Ex; /* Prevent compiler warnings */
    ruleT__24Ex: ;

}
// $ANTLR end T__24

//   Comes from: 8:7: ( '&' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__25
 *
 * Looks to match the characters the constitute the token T__25
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__25(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__25;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:8:7: ( '&' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:8:9: '&'
    {
        MATCHC('&'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__25Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__25Ex; /* Prevent compiler warnings */
    ruleT__25Ex: ;

}
// $ANTLR end T__25

//   Comes from: 9:7: ( '$' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__26
 *
 * Looks to match the characters the constitute the token T__26
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__26(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__26;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:9:7: ( '$' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:9:9: '$'
    {
        MATCHC('$'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__26Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__26Ex; /* Prevent compiler warnings */
    ruleT__26Ex: ;

}
// $ANTLR end T__26

//   Comes from: 10:7: ( '?' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__27
 *
 * Looks to match the characters the constitute the token T__27
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__27(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__27;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:10:7: ( '?' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:10:9: '?'
    {
        MATCHC('?'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__27Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__27Ex; /* Prevent compiler warnings */
    ruleT__27Ex: ;

}
// $ANTLR end T__27

//   Comes from: 11:7: ( '.' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__28
 *
 * Looks to match the characters the constitute the token T__28
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__28(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__28;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:11:7: ( '.' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:11:9: '.'
    {
        MATCHC('.'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__28Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__28Ex; /* Prevent compiler warnings */
    ruleT__28Ex: ;

}
// $ANTLR end T__28

//   Comes from: 12:7: ( '-' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__29
 *
 * Looks to match the characters the constitute the token T__29
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__29(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__29;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:12:7: ( '-' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:12:9: '-'
    {
        MATCHC('-'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__29Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__29Ex; /* Prevent compiler warnings */
    ruleT__29Ex: ;

}
// $ANTLR end T__29

//   Comes from: 13:7: ( '[' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__30
 *
 * Looks to match the characters the constitute the token T__30
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__30(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__30;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:13:7: ( '[' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:13:9: '['
    {
        MATCHC('['); 
        if  (HASEXCEPTION())
        {
            goto ruleT__30Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__30Ex; /* Prevent compiler warnings */
    ruleT__30Ex: ;

}
// $ANTLR end T__30

//   Comes from: 14:7: ( ']' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__31
 *
 * Looks to match the characters the constitute the token T__31
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__31(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__31;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:14:7: ( ']' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:14:9: ']'
    {
        MATCHC(']'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__31Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__31Ex; /* Prevent compiler warnings */
    ruleT__31Ex: ;

}
// $ANTLR end T__31

//   Comes from: 15:7: ( '::' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__32
 *
 * Looks to match the characters the constitute the token T__32
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__32(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__32;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:15:7: ( '::' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:15:9: '::'
    {
        MATCHS(lit_1); 
        if  (HASEXCEPTION())
        {
            goto ruleT__32Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__32Ex; /* Prevent compiler warnings */
    ruleT__32Ex: ;

}
// $ANTLR end T__32

//   Comes from: 16:7: ( '|' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__33
 *
 * Looks to match the characters the constitute the token T__33
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__33(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__33;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:16:7: ( '|' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:16:9: '|'
    {
        MATCHC('|'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__33Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__33Ex; /* Prevent compiler warnings */
    ruleT__33Ex: ;

}
// $ANTLR end T__33

//   Comes from: 17:7: ( '%' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__34
 *
 * Looks to match the characters the constitute the token T__34
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__34(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__34;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:17:7: ( '%' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:17:9: '%'
    {
        MATCHC('%'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__34Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__34Ex; /* Prevent compiler warnings */
    ruleT__34Ex: ;

}
// $ANTLR end T__34

//   Comes from: 18:7: ( '`' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__35
 *
 * Looks to match the characters the constitute the token T__35
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__35(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__35;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:18:7: ( '`' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:18:9: '`'
    {
        MATCHC('`'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__35Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__35Ex; /* Prevent compiler warnings */
    ruleT__35Ex: ;

}
// $ANTLR end T__35

//   Comes from: 19:7: ( '\\\\' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__36
 *
 * Looks to match the characters the constitute the token T__36
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__36(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__36;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:19:7: ( '\\\\' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:19:9: '\\\\'
    {
        MATCHC('\\'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__36Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__36Ex; /* Prevent compiler warnings */
    ruleT__36Ex: ;

}
// $ANTLR end T__36

//   Comes from: 20:7: ( '{' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__37
 *
 * Looks to match the characters the constitute the token T__37
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__37(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__37;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:20:7: ( '{' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:20:9: '{'
    {
        MATCHC('{'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__37Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__37Ex; /* Prevent compiler warnings */
    ruleT__37Ex: ;

}
// $ANTLR end T__37

//   Comes from: 21:7: ( '}' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__38
 *
 * Looks to match the characters the constitute the token T__38
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__38(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__38;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:21:7: ( '}' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:21:9: '}'
    {
        MATCHC('}'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__38Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__38Ex; /* Prevent compiler warnings */
    ruleT__38Ex: ;

}
// $ANTLR end T__38

//   Comes from: 22:7: ( '_' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__39
 *
 * Looks to match the characters the constitute the token T__39
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__39(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__39;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:22:7: ( '_' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:22:9: '_'
    {
        MATCHC('_'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__39Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__39Ex; /* Prevent compiler warnings */
    ruleT__39Ex: ;

}
// $ANTLR end T__39

//   Comes from: 23:7: ( '!' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__40
 *
 * Looks to match the characters the constitute the token T__40
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__40(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__40;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:23:7: ( '!' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:23:9: '!'
    {
        MATCHC('!'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__40Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__40Ex; /* Prevent compiler warnings */
    ruleT__40Ex: ;

}
// $ANTLR end T__40

//   Comes from: 24:7: ( '~' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__41
 *
 * Looks to match the characters the constitute the token T__41
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__41(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__41;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:24:7: ( '~' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:24:9: '~'
    {
        MATCHC('~'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__41Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__41Ex; /* Prevent compiler warnings */
    ruleT__41Ex: ;

}
// $ANTLR end T__41

//   Comes from: 25:7: ( '\\'' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__42
 *
 * Looks to match the characters the constitute the token T__42
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__42(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__42;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:25:7: ( '\\'' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:25:9: '\\''
    {
        MATCHC('\''); 
        if  (HASEXCEPTION())
        {
            goto ruleT__42Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__42Ex; /* Prevent compiler warnings */
    ruleT__42Ex: ;

}
// $ANTLR end T__42

//   Comes from: 1401:2: ( 'g' .. 'z' | 'G' .. 'Z' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start COMMON_CHAR
 *
 * Looks to match the characters the constitute the token COMMON_CHAR
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCOMMON_CHAR(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = COMMON_CHAR;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1401:2: ( 'g' .. 'z' | 'G' .. 'Z' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:
    {
        if ( ((LA(1) >= 'G') && (LA(1) <= 'Z')) || ((LA(1) >= 'g') && (LA(1) <= 'z')) )
        {
            CONSUME();

        }
        else 
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();    goto ruleCOMMON_CHAREx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleCOMMON_CHAREx; /* Prevent compiler warnings */
    ruleCOMMON_CHAREx: ;

}
// $ANTLR end COMMON_CHAR

//   Comes from: 1405:9: ( 'a' .. 'f' | 'A' .. 'F' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start HEX_CHAR
 *
 * Looks to match the characters the constitute the token HEX_CHAR
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mHEX_CHAR(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = HEX_CHAR;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1405:9: ( 'a' .. 'f' | 'A' .. 'F' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:
    {
        if ( ((LA(1) >= 'A') && (LA(1) <= 'F')) || ((LA(1) >= 'a') && (LA(1) <= 'f')) )
        {
            CONSUME();

        }
        else 
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();    goto ruleHEX_CHAREx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleHEX_CHAREx; /* Prevent compiler warnings */
    ruleHEX_CHAREx: ;

}
// $ANTLR end HEX_CHAR

//   Comes from: 1406:7: ( '0' .. '9' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DIGIT
 *
 * Looks to match the characters the constitute the token DIGIT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mDIGIT(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = DIGIT;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1406:7: ( '0' .. '9' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1406:9: '0' .. '9'
    {
        MATCHRANGE('0', '9'); 
        if  (HASEXCEPTION())
        {
            goto ruleDIGITEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleDIGITEx; /* Prevent compiler warnings */
    ruleDIGITEx: ;

}
// $ANTLR end DIGIT

//   Comes from: 1408:6: ( '\\r\\n' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CRLF
 *
 * Looks to match the characters the constitute the token CRLF
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCRLF(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = CRLF;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1408:6: ( '\\r\\n' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1408:8: '\\r\\n'
    {
        MATCHS(lit_2); 
        if  (HASEXCEPTION())
        {
            goto ruleCRLFEx;
        }


        {
             USER1 = (int)((char*)ctx->pLexer->input->currentLine - (char*)ctx->pLexer->input->data); /*GETCHARINDEX()*/;
        }

    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleCRLFEx; /* Prevent compiler warnings */
    ruleCRLFEx: ;

}
// $ANTLR end CRLF

//   Comes from: 1416:6: ( '\t' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start HTAB
 *
 * Looks to match the characters the constitute the token HTAB
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mHTAB(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = HTAB;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1416:6: ( '\t' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1416:8: '\t'
    {
        MATCHC(0x9); 
        if  (HASEXCEPTION())
        {
            goto ruleHTABEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleHTABEx; /* Prevent compiler warnings */
    ruleHTABEx: ;

}
// $ANTLR end HTAB

//   Comes from: 1426:8: ( '\"' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DQUOTE
 *
 * Looks to match the characters the constitute the token DQUOTE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mDQUOTE(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = DQUOTE;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1426:8: ( '\"' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1426:10: '\"'
    {
        MATCHC('"'); 
        if  (HASEXCEPTION())
        {
            goto ruleDQUOTEEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleDQUOTEEx; /* Prevent compiler warnings */
    ruleDQUOTEEx: ;

}
// $ANTLR end DQUOTE

//   Comes from: 1431:7: ( ( ( SP )* CRLF )? ( SP )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LWS
 *
 * Looks to match the characters the constitute the token LWS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLWS(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = LWS;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1431:7: ( ( ( SP )* CRLF )? ( SP )+ )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1431:9: ( ( SP )* CRLF )? ( SP )+
    {

        // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1431:9: ( ( SP )* CRLF )?
        {
            int alt2=2;
            alt2 = cdfa2.predict(ctx, RECOGNIZER, ISTREAM, &cdfa2);
            if  (HASEXCEPTION())
            {
                goto ruleLWSEx;
            }

            switch (alt2) 
            {
        	case 1:
        	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1431:10: ( SP )* CRLF
        	    {

        	        // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1431:10: ( SP )*

        	        for (;;)
        	        {
        	            int alt1=2;
        	            switch ( LA(1) ) 
        	            {
        	            case ' ':
        	            	{
        	            		alt1=1;
        	            	}
        	                break;

        	            }

        	            switch (alt1) 
        	            {
        	        	case 1:
        	        	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1431:10: SP
        	        	    {
        	        	        /* 1431:10: SP */
        	        	        mSP(ctx ); 
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruleLWSEx;
        	        	        }


        	        	    }
        	        	    break;

        	        	default:
        	        	    goto loop1;	/* break out of the loop */
        	        	    break;
        	            }
        	        }
        	        loop1: ; /* Jump out to here if this rule does not match */

        	        /* 1431:10: ( SP )* CRLF */
        	        mCRLF(ctx ); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleLWSEx;
        	        }


        	    }
        	    break;

            }
        }
        // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1431:21: ( SP )+
        {
            int cnt3=0;

            for (;;)
            {
                int alt3=2;
        	switch ( LA(1) ) 
        	{
        	case ' ':
        		{
        			alt3=1;
        		}
        	    break;

        	}

        	switch (alt3) 
        	{
        	    case 1:
        	        // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1431:21: SP
        	        {
        	            /* 1431:21: SP */
        	            mSP(ctx ); 
        	            if  (HASEXCEPTION())
        	            {
        	                goto ruleLWSEx;
        	            }


        	        }
        	        break;

        	    default:
        	    
        		if ( cnt3 >= 1 )
        		{
        		    goto loop3;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleLWSEx;
        	}
        	cnt3++;
            }
            loop3: ;	/* Jump to here if this rule does not match */
        }

    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleLWSEx; /* Prevent compiler warnings */
    ruleLWSEx: ;

}
// $ANTLR end LWS

//   Comes from: 1437:5: ( '+' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start PLUS
 *
 * Looks to match the characters the constitute the token PLUS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mPLUS(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = PLUS;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1437:5: ( '+' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1437:7: '+'
    {
        MATCHC('+'); 
        if  (HASEXCEPTION())
        {
            goto rulePLUSEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto rulePLUSEx; /* Prevent compiler warnings */
    rulePLUSEx: ;

}
// $ANTLR end PLUS

//   Comes from: 1441:2: ( ':' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start COLON
 *
 * Looks to match the characters the constitute the token COLON
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCOLON(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = COLON;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1441:2: ( ':' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1441:4: ':'
    {
        MATCHC(':'); 
        if  (HASEXCEPTION())
        {
            goto ruleCOLONEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleCOLONEx; /* Prevent compiler warnings */
    ruleCOLONEx: ;

}
// $ANTLR end COLON

//   Comes from: 1446:2: ( ';' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start SEMI
 *
 * Looks to match the characters the constitute the token SEMI
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSEMI(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = SEMI;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1446:2: ( ';' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1446:4: ';'
    {
        MATCHC(';'); 
        if  (HASEXCEPTION())
        {
            goto ruleSEMIEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleSEMIEx; /* Prevent compiler warnings */
    ruleSEMIEx: ;

}
// $ANTLR end SEMI

//   Comes from: 1451:2: ( ',' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start COMMA
 *
 * Looks to match the characters the constitute the token COMMA
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCOMMA(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = COMMA;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1451:2: ( ',' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1451:4: ','
    {
        MATCHC(','); 
        if  (HASEXCEPTION())
        {
            goto ruleCOMMAEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleCOMMAEx; /* Prevent compiler warnings */
    ruleCOMMAEx: ;

}
// $ANTLR end COMMA

//   Comes from: 1459:2: ( '<' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LAQUOT
 *
 * Looks to match the characters the constitute the token LAQUOT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLAQUOT(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = LAQUOT;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1459:2: ( '<' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1459:4: '<'
    {
        MATCHC('<'); 
        if  (HASEXCEPTION())
        {
            goto ruleLAQUOTEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleLAQUOTEx; /* Prevent compiler warnings */
    ruleLAQUOTEx: ;

}
// $ANTLR end LAQUOT

//   Comes from: 1463:2: ( '>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start RAQUOT
 *
 * Looks to match the characters the constitute the token RAQUOT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mRAQUOT(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = RAQUOT;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1463:2: ( '>' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1463:4: '>'
    {
        MATCHC('>'); 
        if  (HASEXCEPTION())
        {
            goto ruleRAQUOTEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleRAQUOTEx; /* Prevent compiler warnings */
    ruleRAQUOTEx: ;

}
// $ANTLR end RAQUOT

//   Comes from: 1467:2: ( ')' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start RPAREN
 *
 * Looks to match the characters the constitute the token RPAREN
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mRPAREN(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = RPAREN;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1467:2: ( ')' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1467:4: ')'
    {
        MATCHC(')'); 
        if  (HASEXCEPTION())
        {
            goto ruleRPARENEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleRPARENEx; /* Prevent compiler warnings */
    ruleRPARENEx: ;

}
// $ANTLR end RPAREN

//   Comes from: 1471:2: ( '(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LPAREN
 *
 * Looks to match the characters the constitute the token LPAREN
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLPAREN(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = LPAREN;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1471:2: ( '(' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1471:4: '('
    {
        MATCHC('('); 
        if  (HASEXCEPTION())
        {
            goto ruleLPARENEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleLPARENEx; /* Prevent compiler warnings */
    ruleLPARENEx: ;

}
// $ANTLR end LPAREN

//   Comes from: 1477:2: ( '=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start EQUAL
 *
 * Looks to match the characters the constitute the token EQUAL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mEQUAL(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = EQUAL;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1477:2: ( '=' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1477:4: '='
    {
        MATCHC('='); 
        if  (HASEXCEPTION())
        {
            goto ruleEQUALEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleEQUALEx; /* Prevent compiler warnings */
    ruleEQUALEx: ;

}
// $ANTLR end EQUAL

//   Comes from: 1482:2: ( '/' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start SLASH
 *
 * Looks to match the characters the constitute the token SLASH
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSLASH(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = SLASH;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1482:2: ( '/' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1482:4: '/'
    {
        MATCHC('/'); 
        if  (HASEXCEPTION())
        {
            goto ruleSLASHEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleSLASHEx; /* Prevent compiler warnings */
    ruleSLASHEx: ;

}
// $ANTLR end SLASH

//   Comes from: 1486:2: ( '*' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start STAR
 *
 * Looks to match the characters the constitute the token STAR
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSTAR(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = STAR;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1486:2: ( '*' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1486:4: '*'
    {
        MATCHC('*'); 
        if  (HASEXCEPTION())
        {
            goto ruleSTAREx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleSTAREx; /* Prevent compiler warnings */
    ruleSTAREx: ;

}
// $ANTLR end STAR

//   Comes from: 1490:2: ( ' ' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start SP
 *
 * Looks to match the characters the constitute the token SP
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSP(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

        
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1490:2: ( ' ' )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1490:4: ' '
    {
        MATCHC(' '); 
        if  (HASEXCEPTION())
        {
            goto ruleSPEx;
        }


    }



    // This is where rules clean up and exit
    //
    goto ruleSPEx; /* Prevent compiler warnings */
    ruleSPEx: ;

}
// $ANTLR end SP

//   Comes from: 1492:7: ( . )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OCTET
 *
 * Looks to match the characters the constitute the token OCTET
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOCTET(pbelle_sip_messageLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OCTET;
       
    
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1492:7: ( . )
    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1492:9: .
    {
        MATCHANY(); 
        if  (HASEXCEPTION())
        {
            goto ruleOCTETEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleOCTETEx; /* Prevent compiler warnings */
    ruleOCTETEx: ;

}
// $ANTLR end OCTET

/** This is the entry point in to the lexer from an object that
 *  wants to generate the next token, such as a pCOMMON_TOKEN_STREAM
 */
static void 
mTokens(pbelle_sip_messageLexer ctx)
{
    {
        //  /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:8: ( T__24 | T__25 | T__26 | T__27 | T__28 | T__29 | T__30 | T__31 | T__32 | T__33 | T__34 | T__35 | T__36 | T__37 | T__38 | T__39 | T__40 | T__41 | T__42 | COMMON_CHAR | HEX_CHAR | DIGIT | CRLF | HTAB | DQUOTE | LWS | PLUS | COLON | SEMI | COMMA | LAQUOT | RAQUOT | RPAREN | LPAREN | EQUAL | SLASH | STAR | OCTET )
        
        ANTLR3_UINT32 alt4;

        alt4=38;


        {
            int LA4_0 = LA(1);
            if ( (LA4_0 == '@') ) 
            {
                alt4=1;
            }
            else if ( (LA4_0 == '&') ) 
            {
                alt4=2;
            }
            else if ( (LA4_0 == '$') ) 
            {
                alt4=3;
            }
            else if ( (LA4_0 == '?') ) 
            {
                alt4=4;
            }
            else if ( (LA4_0 == '.') ) 
            {
                alt4=5;
            }
            else if ( (LA4_0 == '-') ) 
            {
                alt4=6;
            }
            else if ( (LA4_0 == '[') ) 
            {
                alt4=7;
            }
            else if ( (LA4_0 == ']') ) 
            {
                alt4=8;
            }
            else if ( (LA4_0 == ':') ) 
            {
                switch ( LA(2) ) 
                {
                case ':':
                	{
                		alt4=9;
                	}
                    break;

                default:
                    alt4=28;}

            }
            else if ( (LA4_0 == '|') ) 
            {
                alt4=10;
            }
            else if ( (LA4_0 == '%') ) 
            {
                alt4=11;
            }
            else if ( (LA4_0 == '`') ) 
            {
                alt4=12;
            }
            else if ( (LA4_0 == '\\') ) 
            {
                alt4=13;
            }
            else if ( (LA4_0 == '{') ) 
            {
                alt4=14;
            }
            else if ( (LA4_0 == '}') ) 
            {
                alt4=15;
            }
            else if ( (LA4_0 == '_') ) 
            {
                alt4=16;
            }
            else if ( (LA4_0 == '!') ) 
            {
                alt4=17;
            }
            else if ( (LA4_0 == '~') ) 
            {
                alt4=18;
            }
            else if ( (LA4_0 == '\'') ) 
            {
                alt4=19;
            }
            else if ( (((LA4_0 >= 'G') && (LA4_0 <= 'Z')) || ((LA4_0 >= 'g') && (LA4_0 <= 'z'))) ) 
            {
                alt4=20;
            }
            else if ( (((LA4_0 >= 'A') && (LA4_0 <= 'F')) || ((LA4_0 >= 'a') && (LA4_0 <= 'f'))) ) 
            {
                alt4=21;
            }
            else if ( (((LA4_0 >= '0') && (LA4_0 <= '9'))) ) 
            {
                alt4=22;
            }
            else if ( (LA4_0 == '\r') ) 
            {
                switch ( LA(2) ) 
                {
                case '\n':
                	{
                		switch ( LA(3) ) 
                		{
                		case ' ':
                			{
                				alt4=26;
                			}
                		    break;

                		default:
                		    alt4=23;}

                	}
                    break;

                default:
                    alt4=38;}

            }
            else if ( (LA4_0 == '\t') ) 
            {
                alt4=24;
            }
            else if ( (LA4_0 == '"') ) 
            {
                alt4=25;
            }
            else if ( (LA4_0 == ' ') ) 
            {
                alt4=26;
            }
            else if ( (LA4_0 == '+') ) 
            {
                alt4=27;
            }
            else if ( (LA4_0 == ';') ) 
            {
                alt4=29;
            }
            else if ( (LA4_0 == ',') ) 
            {
                alt4=30;
            }
            else if ( (LA4_0 == '<') ) 
            {
                alt4=31;
            }
            else if ( (LA4_0 == '>') ) 
            {
                alt4=32;
            }
            else if ( (LA4_0 == ')') ) 
            {
                alt4=33;
            }
            else if ( (LA4_0 == '(') ) 
            {
                alt4=34;
            }
            else if ( (LA4_0 == '=') ) 
            {
                alt4=35;
            }
            else if ( (LA4_0 == '/') ) 
            {
                alt4=36;
            }
            else if ( (LA4_0 == '*') ) 
            {
                alt4=37;
            }
            else if ( (((LA4_0 >= 0x0000) && (LA4_0 <= '\b')) || ((LA4_0 >= '\n') && (LA4_0 <= '\f')) || ((LA4_0 >= 0x000E) && (LA4_0 <= 0x001F)) || LA4_0 == '#' || LA4_0 == '^' || ((LA4_0 >= 0x007F) && (LA4_0 <= 0xFFFF))) ) 
            {
                alt4=38;
            }
            else 
            {
            
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 4;
                EXCEPTION->state        = 0;


                goto ruleTokensEx;
            }
        }
        switch (alt4) 
        {
    	case 1:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:10: T__24
    	    {
    	        /* 1:10: T__24 */
    	        mT__24(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 2:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:16: T__25
    	    {
    	        /* 1:16: T__25 */
    	        mT__25(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 3:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:22: T__26
    	    {
    	        /* 1:22: T__26 */
    	        mT__26(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 4:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:28: T__27
    	    {
    	        /* 1:28: T__27 */
    	        mT__27(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 5:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:34: T__28
    	    {
    	        /* 1:34: T__28 */
    	        mT__28(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 6:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:40: T__29
    	    {
    	        /* 1:40: T__29 */
    	        mT__29(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 7:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:46: T__30
    	    {
    	        /* 1:46: T__30 */
    	        mT__30(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 8:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:52: T__31
    	    {
    	        /* 1:52: T__31 */
    	        mT__31(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 9:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:58: T__32
    	    {
    	        /* 1:58: T__32 */
    	        mT__32(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 10:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:64: T__33
    	    {
    	        /* 1:64: T__33 */
    	        mT__33(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 11:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:70: T__34
    	    {
    	        /* 1:70: T__34 */
    	        mT__34(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 12:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:76: T__35
    	    {
    	        /* 1:76: T__35 */
    	        mT__35(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 13:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:82: T__36
    	    {
    	        /* 1:82: T__36 */
    	        mT__36(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 14:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:88: T__37
    	    {
    	        /* 1:88: T__37 */
    	        mT__37(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 15:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:94: T__38
    	    {
    	        /* 1:94: T__38 */
    	        mT__38(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 16:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:100: T__39
    	    {
    	        /* 1:100: T__39 */
    	        mT__39(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 17:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:106: T__40
    	    {
    	        /* 1:106: T__40 */
    	        mT__40(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 18:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:112: T__41
    	    {
    	        /* 1:112: T__41 */
    	        mT__41(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 19:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:118: T__42
    	    {
    	        /* 1:118: T__42 */
    	        mT__42(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 20:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:124: COMMON_CHAR
    	    {
    	        /* 1:124: COMMON_CHAR */
    	        mCOMMON_CHAR(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 21:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:136: HEX_CHAR
    	    {
    	        /* 1:136: HEX_CHAR */
    	        mHEX_CHAR(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 22:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:145: DIGIT
    	    {
    	        /* 1:145: DIGIT */
    	        mDIGIT(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 23:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:151: CRLF
    	    {
    	        /* 1:151: CRLF */
    	        mCRLF(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 24:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:156: HTAB
    	    {
    	        /* 1:156: HTAB */
    	        mHTAB(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 25:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:161: DQUOTE
    	    {
    	        /* 1:161: DQUOTE */
    	        mDQUOTE(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 26:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:168: LWS
    	    {
    	        /* 1:168: LWS */
    	        mLWS(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 27:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:172: PLUS
    	    {
    	        /* 1:172: PLUS */
    	        mPLUS(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 28:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:177: COLON
    	    {
    	        /* 1:177: COLON */
    	        mCOLON(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 29:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:183: SEMI
    	    {
    	        /* 1:183: SEMI */
    	        mSEMI(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 30:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:188: COMMA
    	    {
    	        /* 1:188: COMMA */
    	        mCOMMA(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 31:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:194: LAQUOT
    	    {
    	        /* 1:194: LAQUOT */
    	        mLAQUOT(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 32:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:201: RAQUOT
    	    {
    	        /* 1:201: RAQUOT */
    	        mRAQUOT(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 33:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:208: RPAREN
    	    {
    	        /* 1:208: RPAREN */
    	        mRPAREN(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 34:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:215: LPAREN
    	    {
    	        /* 1:215: LPAREN */
    	        mLPAREN(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 35:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:222: EQUAL
    	    {
    	        /* 1:222: EQUAL */
    	        mEQUAL(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 36:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:228: SLASH
    	    {
    	        /* 1:228: SLASH */
    	        mSLASH(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 37:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:234: STAR
    	    {
    	        /* 1:234: STAR */
    	        mSTAR(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 38:
    	    // /Users/karimjimo/Downloads/linphone-iphone/submodules/build/..//belle-sip/src/belle_sip_message.g:1:239: OCTET
    	    {
    	        /* 1:239: OCTET */
    	        mOCTET(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;

        }
    }

    
    goto ruleTokensEx; /* Prevent compiler warnings */
ruleTokensEx: ;
}

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */
/* End of Lexer code
 * ================================================
 * ================================================
 */ 


/* End of code
 * =============================================================================
 */
