.TH "_LinphoneVideoPolicy" 3 "Sun Oct 13 2013" "Version 3.6.99" "liblinphone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_LinphoneVideoPolicy \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <linphonecore\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool_t \fBautomatically_initiate\fP"
.br
.ti -1c
.RI "bool_t \fBautomatically_accept\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure describing policy regarding video streams establishments\&. 
.SH "Field Documentation"
.PP 
.SS "bool_t _LinphoneVideoPolicy::automatically_initiate"
Whether video shall be automatically proposed for outgoing calls\&. 
.SS "bool_t _LinphoneVideoPolicy::automatically_accept"
Whether video shall be automatically accepted for incoming calls 

.SH "Author"
.PP 
Generated automatically by Doxygen for liblinphone from the source code\&.
