.TH "Portability:" 3 "Sun Oct 13 2013" "Version 3.6.99" "liblinphone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Portability: \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBIOS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for liblinphone from the source code\&.
